### ISSUE TITLE
default constructor not found in Kotlin

### ISSUE THREAD

**Issue by gam2046** [alibaba/fastjson#1593]
I've got [this](https://github.com/alibaba/fastjson/wiki/Use-Fastjson-in-Kotlin)

## Data Class

```java
data class Configuration(val signature: String, val last_update: Long, val plugins: List<Plugins>)
```

## Try to serialize

```java
val configuration = JSON.parseObject(jsonString, Configuration::class.javaObjectType)
```

## Exception

```
com.alibaba.fastjson.JSONException: default constructor not found. class packagename.Configuration
   at com.alibaba.fastjson.parser.JavaBeanInfo.build(JavaBeanInfo.java:496)
   at com.alibaba.fastjson.parser.JavaBeanDeserializer.<init>(JavaBeanDeserializer.java:35)
   at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:225)
   at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:144)
   at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:683)
   at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:659)
   at com.alibaba.fastjson.JSON.parseObject(JSON.java:212)
   at com.alibaba.fastjson.JSON.parseObject(JSON.java:184)
   at com.alibaba.fastjson.JSON.parseObject(JSON.java:143)
   at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)
   at packagename.Worker.run(Worker.kt:195)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:841)
```

## Fastjson Version

1.1.64.android

**Comment by wenshao** [comment]
This problem was fixed in version 1.1.67.android.

**Comment by gam2046** [comment]
Thanks for your response.
But I've tried using the `1.1.67.android` version, and it's still the same problem

## Data Class

```kotlin
data class JsonBean(val signature: String, val list: List<Lists>)
data class Lists(val name: String)
```
## Test code

```kotlin
        val jsonString = """
        {
          "signature": "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
          "lists": [
            {
                "name":"aaa"
            },{
                "name":"bbb"
            }
          ]
        }
        """

        try {
            val jsonObject = JSON.parseObject(jsonString, JsonBean::class.javaObjectType)
            println(jsonObject)
        } catch (e: java.lang.Exception) {
            Log.e("fastjson.test", e)
        }
```

## Exception

```
com.alibaba.fastjson.JSONException: default constructor not found. class .JsonBean
   at com.alibaba.fastjson.parser.JavaBeanInfo.build(JavaBeanInfo.java:496)
   at com.alibaba.fastjson.parser.JavaBeanDeserializer.<init>(JavaBeanDeserializer.java:35)
   at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:229)
   at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:148)
   at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:683)
   at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:659)
   at com.alibaba.fastjson.JSON.parseObject(JSON.java:238)
   at com.alibaba.fastjson.JSON.parseObject(JSON.java:210)
   at com.alibaba.fastjson.JSON.parseObject(JSON.java:169)
   at com.alibaba.fastjson.JSON.parseObject(JSON.java:278)
```

**Comment by paulhsu** [comment]
Please also check JSON.toJavaObject(Class<T> clazz)

I got the same error on 1.1.67.android

**Comment by wenshao** [comment]
@gam2046 
```json
"lists": [
```
It should be "list", not "lists"

**Comment by forest-yang** [comment]
I am using Springboot 2.1.1, fastjson 1.2.54,  Kotlin 1.3.11, the problem exists as well.
[Stackoverflow link](https://stackoverflow.com/questions/53983174/kotlin-with-fastjson-parse-object-error-default-constructor-not-found)

PS: when I use gson instead, it works.

```
        /* it will throw exception
        val state = JSON.parseObject(s, StatesMessage::class.java)
        */
        val state = Gson().fromJson(s, StatesMessage::class.java)
        logger.info(state.states.x)
        logger.info(state.states.y)
```

**Comment by wolfhan** [comment]
Try [this](https://github.com/alibaba/fastjson/issues/1569#issuecomment-369467761)

**Comment by 4332weizi** [comment]
什么时候可以修复？
